<div id="info" align="center"></div>
<form action="#" method="post" id="daftar">
  <table width="71%" border="0" align="center">
    <tr>
      <td width="32%">Nama Lengkap Calon PDB </td>
      <td width="1%">:</td>
      <td width="67%">
        <input name="nama" type="text" id="nama" size="30" />      </td>
    </tr>
    <tr>
      <td>No. Induk Siswa Nasional (NISN) </td>
      <td>:</td>
      <td><input name="nisn" type="text" id="nisn" size="10" /><span id="pesan"></span></td>
    </tr>
    <tr>
      <td>Asal Sekolah (SMP/ Sederajat) </td>
      <td>:</td>
      <td><input name="asal_skl" type="text" id="asal_skl" size="40" /></td>
    </tr>
    <tr>
      <td>Email</td>
      <td>:</td>
      <td><input name="email" type="text" id="email" size="40" /></td>
    </tr>
    <tr>
      <td>Gambar Verifikasi </td>
      <td>:</td>
      <td><img src='captcha.php'></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>(Masukan 6 kode diatas)</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>
	   <input name="captcha" type="text" id="captcha" size="8" "/></td>
    </tr>
    <tr>
      <td><input type="submit" id="submit" class="button" value="Daftar" /></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3"><label></label></td>
    </tr>
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="3">&nbsp;</td>
    </tr>
  </table>
</form>
