<div class="content_box">
<div class="col_w270">
	<img src="images/menuMG/daftar.png" width="150" height="110" />
	<h4 class="center">Daftar <span class="color_one">Baru</span></h4>
	<p>Daftar Peserta Didik Baru Online</p><br>
	<p><a href='?module=daftar' class='one_col_btn'>Daftar Baru</a></p>
</div>
<div class="col_w271">
	<img src="images/menuMG/login.png" width="150" height="110" />
	<h4 class="center">Login <span class="color_one">ppdb</span></h4>
	<div id="info" align="center"></div>
	<form action="#" method="post" id="login">
	  <table width="250" border="0">
		<tr>
		  <td width="75">No Peserta</td>
		  <td>:</td>
		  <td><input type="text" id="no_peserta" name="no_peserta" /></td>
		</tr>
		<tr>
		  <td>Password</td>
		  <td>:</td>
		  <td><input type="password"  id="password" name="password" /></td>
		</tr>
		<tr>
		<td colspan='2'><input name='submit' type='submit' id='submit' class='button' value='Login' /></td>
		</tr>
	  </table>
	</form>
 </div>
<div class="col_w270">
	<img src="images/menuMG/pendaftar.png" width="150" height="110" />
	<h4 class="center">Lihat <span class="color_one">Pendaftar</span></h4>
	<p>Daftar Peserta yang telah mendaftar di SMA LOKOMEDIA </p>
	<p><a href="?module=pendaftar" class="one_col_btn">Lihat Pendaftar</a></p>
</div>
<div class="col_w270">
	<img src="images/menuMG/bantuan.png" width="150" height="110"  />
	<h4 class="center">Penjelasan <span class="color_one">PPDB</span></h4>
	<p>Tanya jawab Online dengan panitia PPDB. </p><br>
	<p><a href="?module=pesan" class="one_col_btn">Kirim Pesan</a></p>
</div>
<br class="clear" />
</div>
