<div class="content_box">
	<div class="col_w270">
		<img src="images/menuMG/daftar.png" width="150" height="110" />
		<h4 class="center">Daftar <span class="color_one">Baru</span></h4>
		<p>Daftar Peserta Didik Baru Online</p>
	</div>
	<div class="col_w271c">
		<img src="images/menuMG/pendaftar.png" width="150" height="110" />
		<h4 class="center">Lihat <span class="color_one">Pendaftar</span></h4>
		<p>Daftar Peserta yang telah mendaftar di SMA LOKOMEDIA </p>
		<p><a href="?module=pendaftar" class="one_col_btn">Lihat Pendaftar</a></p>
	</div>
	<div class="col_w271b">
		<img src="images/menuMG/bantuan.png" width="150" height="110"  />
		<h4 class="center">Penjelasan <span class="color_one">PPDB</span></h4>
		<p>Tanya jawab Online dengan panitia PPDB. </p><br>
		<p><a href="?module=pesan" class="one_col_btn">Kirim Pesan</a></p>
	</div>
<br class="clear" />
</div>
