<div class="content_box">
<div class="col_w271l">
<h4 class="center">Login <span class="color_one">ppdb</span></h4>
<div id="info" align="center"></div>

<form action="#" method="post" id="login">
  <table width="300" border="0">
	<tr>
	  <td width="75">No Peserta</td>
	  <td width="3">:</td>
	  <td width="144"><input type="text" id="no_peserta" name="no_peserta" /></td>
	</tr>
	<tr>
	  <td width="75">Password</td>
	  <td width="3">:</td>
	  <td width="144"><input type="password"  id="password" name="password" /></td>
	</tr>
	<tr>
	  <td colspan="2"><input name="submit" type="submit" id="submit" class="button" value="Login" /></td>
	</tr>
  </table>
</form>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</div>
</div>