<div class="content_box">
	<div class="col_w270">
		<img src="images/menuMG/biodat1.png" width="150" height="110" />
		<h4 class="center">lengkapi <span class="color_one">biodata</span></h4>
		<p>Silahkan untuk melengkapi biodata Anda.</p><br /><br />
		<p><a href="?module=biodata&id=1" class="button">Lengkapi Biodata</a></p>
	</div>
	<div class="col_w271c">
		<img src="images/menuMG/rapor.png" width="150" height="110" />
		<h4 class="center">masukan <span class="color_one">nilai rapor</span></h4>
		<p>Silahkan untuk mengisi nilai rapor, nilai rapor tidak boleh kurang dari 75</p><br />
		<p><a href="?module=rapor&id=2" class="button">Nilai Rapor</a></p>
	</div>
	<div class="col_w271b">
		<img src="images/menuMG/cetak1.png" width="150" height="110"  />
		<h4 class="center">Cetak <span class="color_one">Dokumen</span></h4>
		<p>Anda dapat mencetak dokumen setelah mengisi biodata. </p>
		<br />
		<p><a href="?module=dokumen&id=3" class="button">Cetak Dokumen </a></p><br />
	</div>
	<br class="clear" />
</div>
